packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  '@mantine/core': ^8.3.13
  '@tanstack/react-query': ^5.90.20
  '@tanstack/react-query-devtools': ^5.91.2
  "@types/react": ^19.2.5
  "@types/react-dom": ^19.2.3
  "@mantine/hooks": ^8.3.10
  typescript: ^5.9.3
  typescript-eslint: "^8.46.4"
  vite: ^7.2.4
  postcss-simple-vars: ^7.0.1
  '@vitejs/plugin-react': ^5.1.1
  postcss: ^8.5.6
  '@types/node': ^24.10.1
  "eslint-plugin-react-hooks": ^7.0.1
  "eslint-plugin-react-refresh": ^0.4.24
  "@eslint/js": ^9.39.1
  "eslint": ^9.39.1
  "@tanstack/react-router": ^1.147.1
  "postcss-preset-mantine": ^1.18.0

