packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  '@mantine/core': ^8.3.13
  '@tanstack/react-query': ^5.90.20
  '@tanstack/react-query-devtools': ^5.91.2
  "@types/react": ^19.2.5
  "@types/react-dom": ^19.2.3
  "@mantine/hooks": ^8.3.10
  typescript: ^5.9.3
